// AUTO-GENERATED by extract_real_data.js — DO NOT EDIT MANUALLY
// Real 2026 Wimbledon Championships data
const REAL_DATA = {
  "arrivalHours": [
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22
  ],
  "arrivalCounts": [
    6995,
    14160,
    26258,
    35640,
    135514,
    131099,
    112718,
    79104,
    54514,
    45257,
    41427,
    46390,
    51997,
    52505,
    36194,
    19908,
    16399
  ],
  "totalScans": 918141,
  "gateVolumes": [
    {
      "gate": "Gate 5",
      "total": 155621
    },
    {
      "gate": "Gate 3",
      "total": 104871
    },
    {
      "gate": "Gate 13",
      "total": 90918
    },
    {
      "gate": "Gate 4",
      "total": 87611
    },
    {
      "gate": "Gate 1D",
      "total": 70200
    },
    {
      "gate": "Gate 1",
      "total": 46236
    },
    {
      "gate": "Gate 1A",
      "total": 41598
    },
    {
      "gate": "Gate 12",
      "total": 39332
    }
  ],
  "blockVolumes": [
    {
      "block": "CHA.GENERAL.ACCESS",
      "total": 492172
    },
    {
      "block": "GP",
      "total": 118221
    },
    {
      "block": "15",
      "total": 5644
    },
    {
      "block": "117",
      "total": 5580
    },
    {
      "block": "139",
      "total": 5360
    },
    {
      "block": "113",
      "total": 5343
    },
    {
      "block": "127",
      "total": 5342
    },
    {
      "block": "19",
      "total": 5260
    },
    {
      "block": "MEMBER__ACESSS",
      "total": 5243
    },
    {
      "block": "SOU.GENERAL.ACCESS",
      "total": 5175
    },
    {
      "block": "135",
      "total": 4970
    },
    {
      "block": "131",
      "total": 4883
    },
    {
      "block": "123",
      "total": 4641
    },
    {
      "block": "121",
      "total": 4568
    },
    {
      "block": "11",
      "total": 4500
    },
    {
      "block": "143",
      "total": 4449
    },
    {
      "block": "CC301",
      "total": 4071
    },
    {
      "block": "CC204",
      "total": 4063
    },
    {
      "block": "213",
      "total": 3979
    },
    {
      "block": "CC313",
      "total": 3976
    },
    {
      "block": "CC312",
      "total": 3883
    },
    {
      "block": "26",
      "total": 3864
    },
    {
      "block": "CC314",
      "total": 3792
    },
    {
      "block": "CC203",
      "total": 3761
    },
    {
      "block": "24",
      "total": 3705
    },
    {
      "block": "211",
      "total": 3653
    },
    {
      "block": "25",
      "total": 3637
    },
    {
      "block": "RPG.GENERAL.ACCESS",
      "total": 3627
    },
    {
      "block": "120",
      "total": 3521
    },
    {
      "block": "CC210",
      "total": 3379
    },
    {
      "block": "136",
      "total": 3186
    },
    {
      "block": "CC202",
      "total": 3167
    },
    {
      "block": "118",
      "total": 3123
    },
    {
      "block": "212",
      "total": 3095
    },
    {
      "block": "CC316",
      "total": 3022
    },
    {
      "block": "12",
      "total": 3017
    },
    {
      "block": "22",
      "total": 3002
    },
    {
      "block": "CC318",
      "total": 2894
    },
    {
      "block": "CC309",
      "total": 2836
    },
    {
      "block": "16",
      "total": 2818
    },
    {
      "block": "21",
      "total": 2810
    },
    {
      "block": "132",
      "total": 2791
    },
    {
      "block": "CC303",
      "total": 2779
    },
    {
      "block": "CC511",
      "total": 2778
    },
    {
      "block": "CC206",
      "total": 2750
    },
    {
      "block": "CC304",
      "total": 2708
    },
    {
      "block": "CC518",
      "total": 2686
    },
    {
      "block": "CC207",
      "total": 2660
    },
    {
      "block": "CC508",
      "total": 2590
    },
    {
      "block": "CC311",
      "total": 2573
    },
    {
      "block": "116",
      "total": 2521
    },
    {
      "block": "114",
      "total": 2518
    },
    {
      "block": "14",
      "total": 2455
    },
    {
      "block": "CC114",
      "total": 2436
    },
    {
      "block": "CC506",
      "total": 2434
    },
    {
      "block": "CC510",
      "total": 2426
    },
    {
      "block": "CC519",
      "total": 2417
    },
    {
      "block": "128",
      "total": 2383
    },
    {
      "block": "134",
      "total": 2382
    },
    {
      "block": "CC509",
      "total": 2379
    },
    {
      "block": "23",
      "total": 2357
    },
    {
      "block": "CC520",
      "total": 2343
    },
    {
      "block": "CC512",
      "total": 2339
    },
    {
      "block": "CC306",
      "total": 2335
    },
    {
      "block": "110",
      "total": 2334
    },
    {
      "block": "27",
      "total": 2270
    },
    {
      "block": "CC305",
      "total": 2258
    },
    {
      "block": "CC315",
      "total": 2253
    },
    {
      "block": "CC307",
      "total": 2223
    },
    {
      "block": "210",
      "total": 2215
    },
    {
      "block": "CC513",
      "total": 2192
    },
    {
      "block": "CC502",
      "total": 2180
    },
    {
      "block": "CC111",
      "total": 2170
    },
    {
      "block": "CC503",
      "total": 2140
    },
    {
      "block": "CC504",
      "total": 2103
    },
    {
      "block": "CC310",
      "total": 2073
    },
    {
      "block": "CC208",
      "total": 2041
    },
    {
      "block": "18",
      "total": 1992
    },
    {
      "block": "CC113",
      "total": 1986
    },
    {
      "block": "CC317",
      "total": 1979
    },
    {
      "block": "126",
      "total": 1935
    },
    {
      "block": "CC505",
      "total": 1915
    },
    {
      "block": "CC102",
      "total": 1863
    },
    {
      "block": "13",
      "total": 1765
    },
    {
      "block": "CC105",
      "total": 1735
    },
    {
      "block": "112",
      "total": 1728
    },
    {
      "block": "29",
      "total": 1727
    },
    {
      "block": "31",
      "total": 1717
    },
    {
      "block": "130",
      "total": 1694
    },
    {
      "block": "133",
      "total": 1691
    },
    {
      "block": "28",
      "total": 1675
    },
    {
      "block": "141",
      "total": 1661
    },
    {
      "block": "CC104",
      "total": 1657
    },
    {
      "block": "137",
      "total": 1647
    },
    {
      "block": "CC522",
      "total": 1606
    },
    {
      "block": "CC308",
      "total": 1595
    },
    {
      "block": "17",
      "total": 1588
    },
    {
      "block": "119",
      "total": 1580
    },
    {
      "block": "CC516",
      "total": 1548
    },
    {
      "block": "129",
      "total": 1519
    },
    {
      "block": "111",
      "total": 1517
    },
    {
      "block": "CC212",
      "total": 1479
    },
    {
      "block": "125",
      "total": 1469
    },
    {
      "block": "CC103",
      "total": 1455
    },
    {
      "block": "115",
      "total": 1407
    },
    {
      "block": "310",
      "total": 1373
    },
    {
      "block": "CC515",
      "total": 1354
    },
    {
      "block": "122",
      "total": 1346
    },
    {
      "block": "CC205",
      "total": 1343
    },
    {
      "block": "CC514",
      "total": 1340
    },
    {
      "block": "CC523",
      "total": 1335
    },
    {
      "block": "214",
      "total": 1308
    },
    {
      "block": "CC302",
      "total": 1274
    },
    {
      "block": "CC501",
      "total": 1229
    },
    {
      "block": "32",
      "total": 833
    },
    {
      "block": "CC112",
      "total": 768
    },
    {
      "block": "CC106",
      "total": 582
    },
    {
      "block": "124",
      "total": 495
    },
    {
      "block": "CC101",
      "total": 485
    },
    {
      "block": "CC107",
      "total": 469
    },
    {
      "block": "0112EW",
      "total": 167
    },
    {
      "block": "018EW",
      "total": 160
    },
    {
      "block": "CC517",
      "total": 157
    },
    {
      "block": "0130WW",
      "total": 153
    },
    {
      "block": "0126WW",
      "total": 142
    },
    {
      "block": "028WC",
      "total": 138
    },
    {
      "block": "029WC",
      "total": 132
    },
    {
      "block": "0126SWC",
      "total": 112
    },
    {
      "block": "CC201",
      "total": 103
    },
    {
      "block": "CC521",
      "total": 100
    },
    {
      "block": "CC507",
      "total": 87
    },
    {
      "block": "CC108",
      "total": 81
    },
    {
      "block": "CC109EOW",
      "total": 74
    },
    {
      "block": "CC209EOW",
      "total": 70
    },
    {
      "block": "03WC",
      "total": 33
    },
    {
      "block": "CC101SWW",
      "total": 26
    },
    {
      "block": "0130NWC",
      "total": 17
    },
    {
      "block": "CC110",
      "total": 1
    }
  ],
  "peakArrivalMinute": "10:01",
  "peakArrivalRate": 3265,
  "zoneHourlyAvg": {
    "The Hill": {
      "0": 1,
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 0,
      "5": 1,
      "6": 2,
      "7": 1,
      "8": 1,
      "9": 1,
      "10": 143,
      "11": 526,
      "12": 1199,
      "13": 1100,
      "14": 1245,
      "15": 1416,
      "16": 1552,
      "17": 1673,
      "18": 1703,
      "19": 1366,
      "20": 1040,
      "21": 477,
      "22": 112,
      "23": 15
    },
    "Tea Lawn": {
      "0": 8,
      "1": 6,
      "2": 6,
      "3": 1,
      "4": 0,
      "5": 0,
      "6": 1,
      "7": 1,
      "8": 2,
      "9": 4,
      "10": 165,
      "11": 251,
      "12": 436,
      "13": 306,
      "14": 310,
      "15": 458,
      "16": 438,
      "17": 439,
      "18": 369,
      "19": 299,
      "20": 203,
      "21": 96,
      "22": 39,
      "23": 15
    },
    "Southern Village": {
      "0": 42,
      "1": 32,
      "2": 32,
      "3": 4,
      "4": 0,
      "5": 0,
      "6": 0,
      "7": 1,
      "8": 1,
      "9": 5,
      "10": 189,
      "11": 314,
      "12": 443,
      "13": 335,
      "14": 333,
      "15": 359,
      "16": 365,
      "17": 388,
      "18": 383,
      "19": 308,
      "20": 202,
      "21": 82,
      "22": 39,
      "23": 59
    },
    "Parkside L1": {
      "0": 0,
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 0,
      "5": 0,
      "6": 0,
      "7": 0,
      "8": 0,
      "9": 0,
      "10": 160,
      "11": 165,
      "12": 233,
      "13": 154,
      "14": 152,
      "15": 197,
      "16": 173,
      "17": 189,
      "18": 176,
      "19": 143,
      "20": 107,
      "21": 50,
      "22": 23,
      "23": 6
    },
    "Parkside L2": {
      "0": 0,
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 0,
      "5": 0,
      "6": 0,
      "7": 0,
      "8": 0,
      "9": 0,
      "10": 28,
      "11": 41,
      "12": 68,
      "13": 47,
      "14": 52,
      "15": 64,
      "16": 51,
      "17": 58,
      "18": 42,
      "19": 30,
      "20": 18,
      "21": 8,
      "22": 4,
      "23": 1
    },
    "Court 2": {
      "0": 76,
      "1": 75,
      "2": 65,
      "3": 6,
      "4": 1,
      "5": 0,
      "6": 0,
      "7": 0,
      "8": 0,
      "9": 3,
      "10": 156,
      "11": 1350,
      "12": 1599,
      "13": 1549,
      "14": 1599,
      "15": 1687,
      "16": 1758,
      "17": 1286,
      "18": 1379,
      "19": 994,
      "20": 398,
      "21": 24,
      "22": 18,
      "23": 17
    }
  },
  "hillDailyPeaks": [
    1767,
    1842,
    1841,
    1638,
    2075,
    2299,
    2038,
    3186,
    2708,
    2531,
    1507,
    2843,
    2395,
    3005
  ],
  "hillGateMinCurve": [
    {
      "bucket": -60,
      "avg": 1
    },
    {
      "bucket": -45,
      "avg": 1
    },
    {
      "bucket": -30,
      "avg": 0
    },
    {
      "bucket": -15,
      "avg": 1
    },
    {
      "bucket": 0,
      "avg": 39
    },
    {
      "bucket": 15,
      "avg": 116
    },
    {
      "bucket": 30,
      "avg": 180
    },
    {
      "bucket": 45,
      "avg": 235
    },
    {
      "bucket": 60,
      "avg": 299
    },
    {
      "bucket": 75,
      "avg": 419
    },
    {
      "bucket": 90,
      "avg": 585
    },
    {
      "bucket": 105,
      "avg": 803
    },
    {
      "bucket": 120,
      "avg": 1037
    },
    {
      "bucket": 135,
      "avg": 1251
    },
    {
      "bucket": 150,
      "avg": 1303
    },
    {
      "bucket": 165,
      "avg": 1189
    },
    {
      "bucket": 180,
      "avg": 1059
    },
    {
      "bucket": 195,
      "avg": 1043
    },
    {
      "bucket": 210,
      "avg": 1111
    },
    {
      "bucket": 225,
      "avg": 1185
    },
    {
      "bucket": 240,
      "avg": 1202
    },
    {
      "bucket": 255,
      "avg": 1235
    },
    {
      "bucket": 270,
      "avg": 1249
    },
    {
      "bucket": 285,
      "avg": 1292
    },
    {
      "bucket": 300,
      "avg": 1359
    }
  ],
  "zoneDayPeak": {
    "Tea Lawn": {
      "1": {
        "occ": 883,
        "util": 0.98
      },
      "2": {
        "occ": 827,
        "util": 0.92
      },
      "3": {
        "occ": 883,
        "util": 0.98
      },
      "4": {
        "occ": 992,
        "util": 1.1
      },
      "5": {
        "occ": 1264,
        "util": 1.4
      },
      "6": {
        "occ": 908,
        "util": 1.01
      },
      "7": {
        "occ": 694,
        "util": 0.77
      },
      "8": {
        "occ": 894,
        "util": 0.99
      },
      "9": {
        "occ": 755,
        "util": 0.84
      },
      "10": {
        "occ": 790,
        "util": 0.88
      },
      "11": {
        "occ": 965,
        "util": 1.07
      },
      "12": {
        "occ": 830,
        "util": 0.92
      },
      "13": {
        "occ": 914,
        "util": 1.02
      },
      "14": {
        "occ": 792,
        "util": 0.88
      }
    },
    "The Hill": {
      "1": {
        "occ": 1767,
        "util": 0.59
      },
      "2": {
        "occ": 1842,
        "util": 0.61
      },
      "3": {
        "occ": 1841,
        "util": 0.61
      },
      "4": {
        "occ": 1638,
        "util": 0.55
      },
      "5": {
        "occ": 2075,
        "util": 0.69
      },
      "6": {
        "occ": 2299,
        "util": 0.77
      },
      "7": {
        "occ": 2038,
        "util": 0.68
      },
      "8": {
        "occ": 3186,
        "util": 1.06
      },
      "9": {
        "occ": 2708,
        "util": 0.9
      },
      "10": {
        "occ": 2531,
        "util": 0.84
      },
      "11": {
        "occ": 1507,
        "util": 0.5
      },
      "12": {
        "occ": 2843,
        "util": 0.95
      },
      "13": {
        "occ": 2395,
        "util": 0.8
      },
      "14": {
        "occ": 3005,
        "util": 1
      }
    },
    "Court 2": {
      "1": {
        "occ": 3325,
        "util": 0.82
      },
      "2": {
        "occ": 3582,
        "util": 0.88
      },
      "3": {
        "occ": 3053,
        "util": 0.75
      },
      "4": {
        "occ": 3112,
        "util": 0.77
      },
      "5": {
        "occ": 3136,
        "util": 0.77
      },
      "6": {
        "occ": 3603,
        "util": 0.89
      },
      "7": {
        "occ": 3212,
        "util": 0.79
      },
      "8": {
        "occ": 3133,
        "util": 0.77
      },
      "9": {
        "occ": 2645,
        "util": 0.65
      },
      "10": {
        "occ": 2586,
        "util": 0.64
      },
      "11": {
        "occ": 1601,
        "util": 0.39
      },
      "12": {
        "occ": 978,
        "util": 0.24
      },
      "13": {
        "occ": 321,
        "util": 0.08
      },
      "14": {
        "occ": 876,
        "util": 0.22
      }
    },
    "Southern Village": {
      "1": {
        "occ": 567,
        "util": 0.76
      },
      "2": {
        "occ": 666,
        "util": 0.89
      },
      "3": {
        "occ": 680,
        "util": 0.91
      },
      "4": {
        "occ": 548,
        "util": 0.73
      },
      "5": {
        "occ": 589,
        "util": 0.79
      },
      "6": {
        "occ": 701,
        "util": 0.93
      },
      "7": {
        "occ": 559,
        "util": 0.75
      },
      "8": {
        "occ": 629,
        "util": 0.84
      },
      "9": {
        "occ": 585,
        "util": 0.78
      },
      "10": {
        "occ": 567,
        "util": 0.76
      },
      "11": {
        "occ": 429,
        "util": 0.57
      },
      "12": {
        "occ": 565,
        "util": 0.75
      },
      "13": {
        "occ": 414,
        "util": 0.55
      },
      "14": {
        "occ": 483,
        "util": 0.64
      }
    },
    "Parkside L2": {
      "1": {
        "occ": 358,
        "util": null
      },
      "2": {
        "occ": 346,
        "util": null
      },
      "3": {
        "occ": 376,
        "util": null
      },
      "4": {
        "occ": 329,
        "util": null
      },
      "5": {
        "occ": 382,
        "util": null
      },
      "6": {
        "occ": 315,
        "util": null
      },
      "7": {
        "occ": 391,
        "util": null
      },
      "8": {
        "occ": 406,
        "util": null
      },
      "9": {
        "occ": 457,
        "util": null
      },
      "10": {
        "occ": 422,
        "util": null
      },
      "11": {
        "occ": 381,
        "util": null
      },
      "12": {
        "occ": 359,
        "util": null
      },
      "13": {
        "occ": 370,
        "util": null
      },
      "14": {
        "occ": 358,
        "util": null
      }
    },
    "Parkside L1": {
      "1": {
        "occ": 721,
        "util": null
      },
      "2": {
        "occ": 704,
        "util": null
      },
      "3": {
        "occ": 735,
        "util": null
      },
      "4": {
        "occ": 634,
        "util": null
      },
      "5": {
        "occ": 735,
        "util": null
      },
      "6": {
        "occ": 707,
        "util": null
      },
      "7": {
        "occ": 736,
        "util": null
      },
      "8": {
        "occ": 664,
        "util": null
      },
      "9": {
        "occ": 696,
        "util": null
      },
      "10": {
        "occ": 845,
        "util": null
      },
      "11": {
        "occ": 602,
        "util": null
      },
      "12": {
        "occ": 523,
        "util": null
      },
      "13": {
        "occ": 589,
        "util": null
      },
      "14": {
        "occ": 686,
        "util": null
      }
    }
  },
  "queueWaits": {
    "fishChips": {
      "0": 0,
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 0,
      "5": 0,
      "6": 0,
      "7": 0,
      "8": 0,
      "9": 0,
      "10": 0,
      "11": 0,
      "12": 0,
      "13": 0,
      "14": 0,
      "15": 0,
      "16": 0,
      "17": 0,
      "18": 0,
      "19": 0,
      "20": 0,
      "21": 0,
      "22": 0,
      "23": 0
    },
    "grill": {
      "0": 0,
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 0,
      "5": 0,
      "6": 0,
      "7": 0,
      "8": 0,
      "9": 0,
      "10": 0,
      "11": 0,
      "12": 0,
      "13": 0,
      "14": 0,
      "15": 0,
      "16": 0,
      "17": 0,
      "18": 0,
      "19": 0,
      "20": 0,
      "21": 0,
      "22": 0,
      "23": 0
    },
    "larder": {
      "0": 0,
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 0,
      "5": 0,
      "6": 0,
      "7": 0,
      "8": 0,
      "9": 0,
      "10": 0,
      "11": 0,
      "12": 0,
      "13": 0,
      "14": 0,
      "15": 0,
      "16": 0,
      "17": 0,
      "18": 0,
      "19": 0,
      "20": 0,
      "21": 0,
      "22": 0,
      "23": 0
    },
    "mainBar": {
      "0": 0,
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 0,
      "5": 0,
      "6": 0,
      "7": 0,
      "8": 0,
      "9": 0,
      "10": 0,
      "11": 0,
      "12": 0,
      "13": 0,
      "14": 0,
      "15": 0,
      "16": 0,
      "17": 0,
      "18": 0,
      "19": 0,
      "20": 0,
      "21": 0,
      "22": 0,
      "23": 0
    }
  },
  "weatherHourly": {
    "0": {
      "temp": 20,
      "wbgt": 0,
      "hum": 61,
      "rain": 0,
      "wind": 5.7
    },
    "1": {
      "temp": 19.1,
      "wbgt": 0,
      "hum": 64,
      "rain": 0,
      "wind": 5.1
    },
    "2": {
      "temp": 18.4,
      "wbgt": 0,
      "hum": 67,
      "rain": 0,
      "wind": 5
    },
    "3": {
      "temp": 17.9,
      "wbgt": 0,
      "hum": 69,
      "rain": 0,
      "wind": 4.9
    },
    "4": {
      "temp": 17.4,
      "wbgt": 0,
      "hum": 71,
      "rain": 0,
      "wind": 5.1
    },
    "5": {
      "temp": 17.2,
      "wbgt": 0,
      "hum": 73,
      "rain": 0,
      "wind": 5.5
    },
    "6": {
      "temp": 17.7,
      "wbgt": 0,
      "hum": 73,
      "rain": 0,
      "wind": 5.8
    },
    "7": {
      "temp": 18.8,
      "wbgt": 0,
      "hum": 70,
      "rain": 0,
      "wind": 6.4
    },
    "8": {
      "temp": 20.1,
      "wbgt": 0,
      "hum": 65,
      "rain": 0,
      "wind": 7.1
    },
    "9": {
      "temp": 21.3,
      "wbgt": 0,
      "hum": 60,
      "rain": 0.02,
      "wind": 7.4
    },
    "10": {
      "temp": 22.8,
      "wbgt": 0,
      "hum": 55,
      "rain": 0,
      "wind": 7.6
    },
    "11": {
      "temp": 23.9,
      "wbgt": 0,
      "hum": 50,
      "rain": 0,
      "wind": 8
    },
    "12": {
      "temp": 25,
      "wbgt": 0,
      "hum": 47,
      "rain": 0,
      "wind": 8.1
    },
    "13": {
      "temp": 25.9,
      "wbgt": 0,
      "hum": 43,
      "rain": 0,
      "wind": 8.3
    },
    "14": {
      "temp": 26.6,
      "wbgt": 0,
      "hum": 41,
      "rain": 0,
      "wind": 8.8
    },
    "15": {
      "temp": 27.3,
      "wbgt": 0,
      "hum": 39,
      "rain": 0,
      "wind": 8.3
    },
    "16": {
      "temp": 27.6,
      "wbgt": 0,
      "hum": 37,
      "rain": 0,
      "wind": 8.3
    },
    "17": {
      "temp": 27.6,
      "wbgt": 0,
      "hum": 37,
      "rain": 0,
      "wind": 8.2
    },
    "18": {
      "temp": 27.1,
      "wbgt": 0,
      "hum": 39,
      "rain": 0,
      "wind": 7.9
    },
    "19": {
      "temp": 26.1,
      "wbgt": 0,
      "hum": 41,
      "rain": 0,
      "wind": 8
    },
    "20": {
      "temp": 24.8,
      "wbgt": 0,
      "hum": 46,
      "rain": 0,
      "wind": 7.2
    },
    "21": {
      "temp": 23.5,
      "wbgt": 0,
      "hum": 51,
      "rain": 0,
      "wind": 7.2
    },
    "22": {
      "temp": 22.3,
      "wbgt": 0,
      "hum": 55,
      "rain": 0,
      "wind": 6.4
    },
    "23": {
      "temp": 21.3,
      "wbgt": 0,
      "hum": 58,
      "rain": 0,
      "wind": 6.5
    }
  },
  "peakTemp": 27.6,
  "peakWBGT": 0,
  "totalRain": 0.02,
  "courtCapacities": {
    "Centre Court": 14979,
    "No.1 Court": 12345,
    "No.2 Court": 4063,
    "No.3 Court": 1980,
    "Court 12": 1065,
    "Court 18": 782
  }
};
